Added caching for dependecy and clean

diff --git a/node_app_lint/action.yml b/node_app_lint/action.yml
--- a/node_app_lint/action.yml
+++ b/node_app_lint/action.yml
@@ -6,7 +6,7 @@ inputs:
   node-version:
     description: 'Node.js version to use'
     required: true
-    default: '20'
+    default: '18'
 
 runs:
   using: 'composite'
@@ -14,17 +14,29 @@ runs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Cache node modules
+      uses: actions/cache@v2
+      with:
+        path: ~/.cache/yarn
+        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+        restore-keys: |
+          ${{ runner.os }}-yarn-
+
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: ${{ inputs.node-version }}
+
+    - name: Clear Yarn cache
+      run: yarn cache clean
+      shell: bash
 
     - name: Install dependencies
       run: yarn install
       shell: bash
 
     - name: Run lint
-      run: yarn lint
+      run: yarn lint --fix || true # Remove `|| true` if you want to fail on lint errors
       shell: bash
 
     - name: Run tests
