Added new Composite Action for lens

diff --git a/django-build-and-scan/action.yml b/django-build-and-scan/action.yml
--- a/django-build-and-scan/action.yml
+++ b/django-build-and-scan/action.yml
@@ -1,4 +1,5 @@
-name: 'Build and Scan Images'
+# django-build-and-scan.yaml (Reusable Action)
+
 description: 'Builds Docker images and scans them for vulnerabilities.'
 inputs:
   github_sha:
@@ -9,6 +10,15 @@ inputs:
     required: true
   cindy_pat:
     description: 'GitHub Personal Access Token'
+    required: true
+  tags:
+    description: 'Docker image tags'
+    required: true
+  file:
+    description: 'Path to Dockerfile for building the first image'
+    required: true
+  context:
+    description: 'Context path for the second image (e.g., Superset)'
     required: true
 
 runs:
@@ -24,8 +34,8 @@ runs:
       uses: docker/build-push-action@v4
       with:
         push: false  
-        tags: lens-damage-prevention:${{ inputs.github_sha }}  
-        file: damage-prevention/support/deployment/Dockerfile
+        tags: ${{ inputs.tags }}
+        file: ${{ inputs.file }}
         build-args: |
           PORT=8080
           GITHUB_AUTH_TOKEN=${{ inputs.cindy_pat }}
@@ -37,7 +47,7 @@ runs:
       uses: docker/build-push-action@v4
       with:
         push: false  
-        context: support/docker/superset
+        context: ${{ inputs.context }}
         tags: lens-superset:${{ inputs.github_sha }}
 
     - name: Cache Trivy DB
@@ -60,14 +70,14 @@ runs:
     - name: Update Trivy DB
       shell: bash  # Specify bash for this shell command
       run: |
-        trivy db update || echo "Failed to update DB, using cached version."
+         trivy --download-db-only || echo "Failed to update DB, using cached version."
 
     - name: Scan Lens Image
       continue-on-error: true
       shell: bash  # Specify bash for this shell command
       run: |
         echo "Scanning Lens Docker image for vulnerabilities..."
-        trivy image --exit-code 1 --severity HIGH,CRITICAL lens-damage-prevention:${{ inputs.github_sha }}
+        trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ inputs.tags }}
 
     - name: Scan Superset Image
       continue-on-error: true
